### ISSUE TITLE
`mavisp` crashes if `entry_not_found.csv` file is not available for the CLINVAR module

### ISSUE THREAD

**Issue by mtiberti** [ELELAB/MAVISp#179]
it should just raise an error in the appropriate entry and continue, instead the error is not correctly handled and it crashes:

```
INFO:mavisp.core:processing module clinvar for VASH1, simple_mode
Traceback (most recent call last):
  File "/usr/local/envs/mavisp/bin/mavisp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/envs/mavisp/lib/python3.7/site-packages/mavisp/mavisp.py", line 141, in main
    mfs.ingest()
  File "/usr/local/envs/mavisp/lib/python3.7/site-packages/mavisp/core.py", line 229, in ingest
    this_module.ingest(mutations['mutation'].tolist())
  File "/usr/local/envs/mavisp/lib/python3.7/site-packages/mavisp/modules.py", line 886, in ingest
    warnings.append(MAVISpWarningError(f"file {self.missing} not found in ClinVar module"))
AttributeError: 'ClinVar' object has no attribute 'missing'
```

**Comment by elenapapaleo** [comment]
this is no longer needed since we changed the source of data for clinvar  for the importing some time ago
